#!/bin/bash

#SBATCH --account=pi-depablo
#SBATCH --time=36:00:00

#SBATCH --partition=depablo-gpu
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=48

#SBATCH --output=LOG/ARO100_T473_P1.ou
#SBATCH --error=LOG/ARO100_T473_P1.err
#SBATCH --job-name=ARO100_T473_P1


######################### LOAD MODULES #########################
module load gromacs/2022.4


######################### VARIABLES #########################
code=ARO   # (ex. EST)
T=473  # temperature (K)
P=1  # pressure (bar)
TIMENPT=10  # time npt run (ns)
TIMENVT=100  # time nvt run (ns)


######################### FILE PATHS #########################
original_gro="../TOP/${code}_original.gro"
gro="../TOP/${code}.gro"
ff="../TOP/OPLS_${code}.top"
MDP="/project2/depablo/achabbi/MDP_TEMPLATES"


######################### MAKE DIRECTORIES #########################
mkdir -p MDP
mkdir -p em
mkdir -p condense
mkdir -p npt
mkdir -p nvt


######################### COPY & MODIFY MDP FILES #########################
cp ${MDP}/* MDP/

sed -i "s/MYTEMP/${T}/g" "MDP/npt.mdp"
sed -i "s/MYPRES/${P}/g" "MDP/npt.mdp"

sed -i "s/MYTEMP/${T}/g" "MDP/nvt.mdp"
sed -i "s/MYPRES/${P}/g" "MDP/nvt.mdp"

nstepsnpt=$(($TIMENPT*1000000))
nstepsnvt=$(($TIMENVT*1000000))
sed -i "s/MYSTEPS/${nstepsnpt}/g" "MDP/npt.mdp"
sed -i "s/MYSTEPS/${nstepsnvt}/g" "MDP/nvt.mdp"


######################### RUN GROMACS #########################
if [ ! -e ${gro} ]; then
	gmx_mpi insert-molecules -ci ${original_gro} -box 50 50 50 -nmol 500 -o ${gro}
fi

gmx_mpi grompp -maxwarn 10 -c ${gro} -f MDP/minimize.mdp -p ${ff} -o em/em.tpr
gmx_mpi mdrun -v -deffnm em/em

gmx_mpi grompp -maxwarn 10 -c em/em.gro -f MDP/condense.mdp -p ${ff} -o condense/condense.tpr
gmx_mpi mdrun -v -deffnm condense/condense

gmx_mpi grompp -maxwarn 10 -c condense/condense.gro -f MDP/npt.mdp -p ${ff} -o npt/npt.tpr
gmx_mpi mdrun -v -deffnm npt/npt

gmx_mpi grompp -maxwarn 10 -c npt/npt.gro -f MDP/nvt.mdp -p ${ff} -o nvt/nvt.tpr
gmx_mpi mdrun -v -deffnm nvt/nvt

#gmx_mpi grompp -maxwarn 10 -c nvt/nvt.gro -f MDP/anneal.mdp -p ${ff} -o anneal/anneal.tpr
#gmx_mpi mdrun -v -deffnm anneal/anneal

